version: '3.9'

services:
  db:
    image: postgres:15
    container_name: users_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: users_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  user-service:
    build: ./services/user-service
    container_name: user_service
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:1234@db:5432/users_db
    ports:
      - "8000:8000"
    volumes:
      - ./services/user-service:/app

volumes:
  postgres_data:
